import {
  IsString,
  IsOptional,
  IsNumber,
  IsInt,
  IsArray,
  IsNotEmpty,
  Min,
  Max,
  MaxLength,
  ArrayMinSize,
  ValidateNested,
} from 'class-validator';
import { Transform, Type } from 'class-transformer';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { trimTransform } from '../../common/transforms';

/**
 * DTO for a single bundle item (product + quantity).
 */
export class BundleItemDto {
  @ApiProperty({
    description: 'Product ID to include in the bundle',
    example: 1,
  })
  @IsInt()
  @Min(1)
  productId!: number;

  @ApiPropertyOptional({
    description: 'Quantity of this product in the bundle',
    example: 2,
    default: 1,
  })
  @IsOptional()
  @IsInt()
  @Min(1)
  quantity?: number = 1;
}

/**
 * DTO for creating a product bundle.
 * Bundle code is auto-generated by the service using BD prefix.
 */
export class CreateProductBundleDto {
  @ApiProperty({
    description: 'Bundle name',
    example: 'Standard Bed Set A',
  })
  @Transform(trimTransform)
  @IsString()
  @IsNotEmpty()
  @MaxLength(200)
  name!: string;

  @ApiPropertyOptional({
    description: 'Bundle description',
    example: 'Includes iron frame, motor, and mattress',
  })
  @Transform(trimTransform)
  @IsOptional()
  @IsString()
  @MaxLength(2000)
  description?: string;

  @ApiPropertyOptional({
    description: 'Total bundle price (2 decimal places)',
    example: 3500.0,
  })
  @IsOptional()
  @IsNumber({ maxDecimalPlaces: 2 })
  @Min(0)
  @Max(99999999.99)
  totalPrice?: number;

  @ApiProperty({
    description: 'Bundle items (at least 1 product required)',
    type: [BundleItemDto],
  })
  @IsArray()
  @ArrayMinSize(1)
  @ValidateNested({ each: true })
  @Type(() => BundleItemDto)
  items!: BundleItemDto[];
}
