import {
  IsString,
  IsOptional,
  IsNumber,
  IsEnum,
  IsNotEmpty,
  IsObject,
  Min,
  Max,
  MaxLength,
} from 'class-validator';
import { Transform } from 'class-transformer';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Prisma } from '@prisma/client';
import { trimTransform } from '../../common/transforms';
import { ProductCategory, ProductSubCategory } from '../../system/enums';

/**
 * DTO for creating a new product.
 * Product code is auto-generated by the service based on subCategory prefix.
 */
export class CreateProductDto {
  @ApiProperty({
    description: 'Product name',
    example: 'Heavy Duty Iron Frame A1',
  })
  @Transform(trimTransform)
  @IsString()
  @IsNotEmpty()
  @MaxLength(200)
  name!: string;

  @ApiProperty({
    description: 'Product category',
    enum: ProductCategory,
    example: ProductCategory.IRON_FRAME_MOTOR,
  })
  @IsEnum(ProductCategory)
  @IsNotEmpty()
  category!: string;

  @ApiProperty({
    description: 'Product sub-category',
    enum: ProductSubCategory,
    example: ProductSubCategory.IRON_FRAME,
  })
  @IsEnum(ProductSubCategory)
  @IsNotEmpty()
  subCategory!: string;

  @ApiPropertyOptional({
    description: 'Model number',
    example: 'TJ-A1-2024',
  })
  @Transform(trimTransform)
  @IsOptional()
  @IsString()
  @MaxLength(100)
  modelNumber?: string;

  @ApiPropertyOptional({
    description: 'Product specification',
    example: '180x200cm, load capacity 300kg',
  })
  @Transform(trimTransform)
  @IsOptional()
  @IsString()
  @MaxLength(500)
  specification?: string;

  @ApiPropertyOptional({
    description: 'Default selling price',
    example: 1200.5,
  })
  @IsOptional()
  @IsNumber({ maxDecimalPlaces: 2 })
  @Min(0)
  @Max(99999999.99)
  defaultPrice?: number;

  @ApiPropertyOptional({
    description: 'Category-specific specs (JSON object)',
    example: { material: 'steel', thickness: '2mm' },
  })
  @IsOptional()
  @IsObject()
  specs?: Prisma.InputJsonValue;

  @ApiPropertyOptional({
    description: 'Additional notes',
    example: 'Best seller in 2024',
  })
  @Transform(trimTransform)
  @IsOptional()
  @IsString()
  @MaxLength(2000)
  notes?: string;
}
