/**
 * Centralized type exports for Borealis Fabrics frontend.
 * Usage: import { Supplier, CreateSupplierData, SupplierStatus } from '@/types';
 */

export type {
  ApiResponse,
  ApiError,
  PaginationMeta,
  PaginatedResult,
  PaginationParams,
  AuthUser,
  LogoutResponse,
  EnumDefinition,
  SystemEnumsResponse,
  HealthResponse,
  AuditLog,
  AuditLogQuery,
  ExportFieldConfig,
  ImportResult,
  ImportFailure,
} from './api.types';

export {
  OrderItemStatus,
  CustomerPayStatus,
  PaymentMethod,
  QuoteStatus,
  SupplierStatus,
  SettleType,
  CreditType,
  PaymentRecordType,
  ProductCategory,
  ProductSubCategory,
  ORDER_ITEM_STATUS_LABELS,
  CUSTOMER_PAY_STATUS_LABELS,
  PAYMENT_METHOD_LABELS,
  QUOTE_STATUS_LABELS,
  SUPPLIER_STATUS_LABELS,
  SETTLE_TYPE_LABELS,
  CREDIT_TYPE_LABELS,
  PAYMENT_RECORD_TYPE_LABELS,
  PRODUCT_CATEGORY_LABELS,
  PRODUCT_SUB_CATEGORY_LABELS,
  STATUS_PRIORITY,
  MODIFIABLE_STATUSES,
} from './enums.types';

export type {
  BaseEntity,
  SoftDeletableEntity,
  User,
  Supplier,
  Address,
  Customer,
  MaterialInfo,
  Fabric,
  FabricSupplier,
  CustomerPricing,
  FabricImage,
  FileEntity,
  Product,
  ProductSupplier,
  ProductPricing,
  QuoteItem,
  Quote,
  Order,
  OrderItem,
  Logistics,
  SupplierPayment,
  PaymentVoucher,
  PaymentRecord,
  OrderTimelineEntry,
} from './entities.types';

export type {
  CreateSupplierData,
  UpdateSupplierData,
  QuerySupplierParams,
  AddressFormData,
  CreateCustomerData,
  UpdateCustomerData,
  QueryCustomerParams,
  MaterialFormData,
  CreateFabricData,
  UpdateFabricData,
  QueryFabricParams,
  CreateFabricSupplierData,
  UpdateFabricSupplierData,
  CreateCustomerPricingData,
  UpdateCustomerPricingData,
  CreateQuoteData,
  UpdateQuoteData,
  QueryQuoteParams,
  AddOrderItemData,
  CreateOrderData,
  UpdateOrderData,
  UpdateOrderItemData,
  UpdateOrderItemStatusData,
  CancelOrderItemData,
  RestoreOrderItemData,
  QueryOrderParams,
  UpdateCustomerPaymentData,
  UpdateSupplierPaymentData,
  CreatePaymentRecordData,
  CreateLogisticsData,
  UpdateLogisticsData,
  QueryLogisticsParams,
  UploadFabricImageData,
  QuerySupplierFabricsParams,
  QueryCustomerOrdersParams,
  QueryFabricSuppliersParams,
  QueryFabricPricingParams,
  CreateFabricPricingData,
  UpdateFabricPricingData,
  CreateProductData,
  UpdateProductData,
  QueryProductParams,
  CreateProductSupplierData,
  UpdateProductSupplierData,
  QueryProductSuppliersParams,
  CreateProductPricingData,
  UpdateProductPricingData,
  QueryProductPricingParams,
  CreateQuoteItemData,
  AddQuoteItemData,
  UpdateQuoteItemData,
  ConvertQuoteItemsData,
} from './forms.types';
